version: "3.8"
services:
    postgres:
        container_name: postgres_gophkeeper
        image: postgres:15-alpine
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_USER}
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - "5432:5432"