version: "3.8"
services:
    postgres:
        container_name: postgres_gophkeeper
        image: postgres:15-alpine
        restart: always
        environment:
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "12345"
            POSTGRES_DB: "gophkeeper"
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - "5432:5432"